// games-data.js  
const GAMES_DATA = {  
  'bloxdhop-io': {  
    title: 'Bloxdhop IO',  
    category: 'action',  
    categoryName: 'Action',  
    stars: '★★★★☆',  
    plays: '245K plays',  
    description: 'Bloxdhop IO is a challenging parkour game where you must navigate through obstacles and compete with other players online. Test your reflexes and timing to become the champion!',  
    developer: 'Bloxdhop Studios',  
    releaseDate: '2021',  
    controls: 'Arrow Keys, WASD',  
    similar: ['playground', 'stickman-epic', 'snake-io'],  
    imageUrl: 'https://img.crazygames.com/games/bloxdhop-io/cover-1591952816196.png'  
  },  
  'crusher-block-jwd': {  
    title: 'Crusher Block',  
    category: 'puzzle',  
    categoryName: 'Puzzle',  
    stars: '★★★★☆',  
    plays: '198K plays',  
    description: 'Crusher Block is a mind-bending puzzle game where you need to crush blocks in the correct order to progress. With increasing difficulty levels, this game will test your strategic thinking.',  
    developer: 'Puzzle Masters',  
    releaseDate: '2022',  
    controls: 'Mouse',  
    similar: ['miniblox', 'polytrack', 'block-wall-destroyer'],  
    imageUrl: 'https://img.crazygames.com/games/crusher-block-jwd/cover-1646130337302.png'  
  },  
  'playground': {  
    title: 'Playground',  
    category: 'action',  
    categoryName: 'Action',  
    stars: '★★★★☆',  
    plays: '176K plays',  
    description: 'Playground is an open-world sandbox game where you can interact with various elements and create your own fun. Experiment with physics and discover hidden surprises!',  
    developer: 'Fun Labs',  
    releaseDate: '2020',  
    controls: 'Mouse, WASD',  
    similar: ['bloxdhop-io', 'fleeing-the-complex', 'stickman-epic'],  
    imageUrl: 'https://img.crazygames.com/games/playground/cover-1584347549326.png'  
  },  
  'miniblox': {  
    title: 'Miniblox',  
    category: 'puzzle',  
    categoryName: 'Puzzle',  
    stars: '★★★☆☆',  
    plays: '132K plays',  
    description: 'Miniblox is a challenging puzzle game where you need to arrange colorful blocks to solve puzzles. With over 100 levels, it will keep you entertained for hours.',  
    developer: 'Block Games',  
    releaseDate: '2020',  
    controls: 'Mouse',  
    similar: ['crusher-block-jwd', 'polytrack', 'block-wall-destroyer'],  
    imageUrl: 'https://img.crazygames.com/games/miniblox/cover-1580743016629.png'  
  },  
  'traffic-rider-vvq': {  
    title: 'Traffic Rider',  
    category: 'racing',  
    categoryName: 'Racing',  
    stars: '★★★★★',  
    plays: '425K plays',  
    description: 'Traffic Rider is an exciting first-person motorcycle racing game where you need to navigate through traffic at high speeds. Complete missions and unlock new bikes!',  
    developer: 'Speed Games',  
    releaseDate: '2019',  
    controls: 'Arrow Keys',  
    similar: ['racing-limits', 'mx-offroad-master', 'smash-karts'],  
    imageUrl: 'https://img.crazygames.com/games/traffic-rider-vvq/cover-1585906866204.png'  
  },  
  'bullet-force-multiplayer': {  
    title: 'Bullet Force Multiplayer',  
    category: 'shooting',  
    categoryName: 'Shooting',  
    stars: '★★★★★',  
    plays: '589K plays',  
    description: 'Bullet Force Multiplayer is an intense first-person shooter with amazing graphics and smooth gameplay. Compete with players worldwide in various game modes.',  
    developer: 'Combat Games',  
    releaseDate: '2018',  
    controls: 'Mouse, WASD',  
    similar: ['skillwarz', 'kour-io', 'k-sniper-challenge-3d'],  
    imageUrl: 'https://img.crazygames.com/games/bullet-force-multiplayer/cover-1583234966241.png'  
  },  
  'piles-of-mahjong-jhb': {  
    title: 'Piles of Mahjong',  
    category: 'puzzle',  
    categoryName: 'Puzzle',  
    stars: '★★★★☆',  
    plays: '376K plays',  
    description: 'Piles of Mahjong is a relaxing tile-matching game where you need to match identical Mahjong tiles to clear the board. With beautiful designs and multiple layouts, it offers hours of fun.',  
    developer: 'Tile Games',  
    releaseDate: '2021',  
    controls: 'Mouse',  
    similar: ['crusher-block-jwd', 'miniblox', 'polytrack'],  
    imageUrl: 'https://img.crazygames.com/games/piles-of-mahjong-jhb/cover-1668514669349.png'  
  },  
  'racing-limits': {  
    title: 'Racing Limits',  
    category: 'racing',  
    categoryName: 'Racing',  
    stars: '★★★★★',  
    plays: '432K plays',  
    description: 'Racing Limits is a high-speed racing game with realistic physics and stunning graphics. Race against the clock or other players to become the ultimate racing champion.',  
    developer: 'Speed Games',  
    releaseDate: '2020',  
    controls: 'Arrow Keys, WASD',  
    similar: ['traffic-rider-vvq', 'mx-offroad-master', 'smash-karts'],  
    imageUrl: 'https://img.crazygames.com/games/racing-limits/cover-1583232264343.png'  
  },  
  'skillwarz': {  
    title: 'Skillwarz',  
    category: 'shooting',  
    categoryName: 'Shooting',  
    stars: '★★★★☆',  
    plays: '321K plays',  
    description: 'Skillwarz is a fast-paced multiplayer shooter where skill matters more than luck. Customize your loadout, join a team, and battle against players from around the world.',  
    developer: 'War Games',  
    releaseDate: '2019',  
    controls: 'Mouse, WASD',  
    similar: ['bullet-force-multiplayer', 'kour-io', 'k-sniper-challenge-3d'],  
    imageUrl: 'https://img.crazygames.com/games/skillwarz/cover-1583401093900.png'  
  },  
  'block-wall-destroyer': {  
    title: 'Block Wall Destroyer',  
    category: 'puzzle',  
    categoryName: 'Puzzle',  
    stars: '★★★★☆',  
    plays: '256K plays',  
    description: 'Block Wall Destroyer is a physics-based puzzle game where you need to destroy blocks by placing bombs strategically. Use your logic to solve increasingly complex levels.',  
    developer: 'Block Games',  
    releaseDate: '2020',  
    controls: 'Mouse',  
    similar: ['crusher-block-jwd', 'miniblox', 'polytrack'],  
    imageUrl: 'https://img.crazygames.com/games/block-wall-destroyer/cover-1584975066414.png'  
  },  
  'polytrack': {  
    title: 'Polytrack',  
    category: 'puzzle',  
    categoryName: 'Puzzle',  
    stars: '★★★★☆',  
    plays: '198K plays',  
    description: 'Polytrack is a minimalist puzzle game where you need to connect nodes by creating tracks between them. With clean design and challenging puzzles, it will test your spatial reasoning.',  
    developer: 'Puzzle Masters',  
    releaseDate: '2019',  
    controls: 'Mouse',  
    similar: ['crusher-block-jwd', 'miniblox', 'block-wall-destroyer'],  
    imageUrl: 'https://img.crazygames.com/games/polytrack/cover-1559725358290.png'  
  },  
  'fleeing-the-complex': {  
    title: 'Fleeing the Complex',  
    category: 'action',  
    categoryName: 'Action',  
    stars: '★★★★★',  
    plays: '345K plays',  
    description: 'Fleeing the Complex is an interactive story-based game where you need to help Henry escape from a high-security prison. Make choices that affect your escape route and outcome.',  
    developer: 'Stickman Studios',  
    releaseDate: '2015',  
    controls: 'Mouse',  
    similar: ['stickman-epic', 'stickman-ww2', 'playground'],  
    imageUrl: 'https://img.crazygames.com/games/fleeing-the-complex/cover-1583235367694.png'  
  },  
  'mx-offroad-master': {  
    title: 'MX Offroad Master',  
    category: 'racing',  
    categoryName: 'Racing',  
    stars: '★★★★☆',  
    plays: '278K plays',  
    description: 'MX Offroad Master is a dirt bike racing game with realistic physics and challenging tracks. Master different terrains and perform stunts to become the offroad champion.',  
    developer: 'Dirt Games',  
    releaseDate: '2019',  
    controls: 'Arrow Keys, WASD',  
    similar: ['traffic-rider-vvq', 'racing-limits', 'smash-karts'],  
    imageUrl: 'https://img.crazygames.com/games/mx-offroad-master/cover-1583235068339.png'  
  },  
  'stickman-epic': {  
    title: 'Stickman Epic',  
    category: 'action',  
    categoryName: 'Action',  
    stars: '★★★★☆',  
    plays: '312K plays',  
    description: 'Stickman Epic is an action-packed fighting game where you control a stickman warrior. Battle against various enemies, upgrade your skills, and become the ultimate fighter.',  
    developer: 'Stickman Studios',  
    releaseDate: '2018',  
    controls: 'Arrow Keys, WASD',  
    similar: ['stickman-ww2', 'fleeing-the-complex', 'playground'],  
    imageUrl: 'https://img.crazygames.com/games/stickman-epic/cover-1583233290522.png'  
  },  
  'stickman-ww2': {  
    title: 'Stickman WW2',  
    category: 'action',  
    categoryName: 'Action',  
    stars: '★★★★☆',  
    plays: '289K plays',  
    description: 'Stickman WW2 is a side-scrolling action game set in World War 2. Lead your stickman troops through various battles, use different weapons, and defeat enemy forces.',  
    developer: 'Stickman Studios',  
    releaseDate: '2019',  
    controls: 'Arrow Keys, WASD, Mouse',  
    similar: ['stickman-epic', 'fleeing-the-complex', 'playground'],  
    imageUrl: 'https://img.crazygames.com/games/stickman-ww2/cover-1583400805574.png'  
  },  
  'k-sniper-challenge-3d': {  
    title: 'K Sniper Challenge 3D',  
    category: 'shooting',  
    categoryName: 'Shooting',  
    stars: '★★★★☆',  
    plays: '267K plays',  
    description: 'K Sniper Challenge 3D is a precision shooting game where you play as an elite sniper. Complete various missions, eliminate targets, and improve your sniping skills.',  
    developer: 'Sniper Games',  
    releaseDate: '2020',  
    controls: 'Mouse',  
    similar: ['bullet-force-multiplayer', 'skillwarz', 'kour-io'],  
    imageUrl: 'https://img.crazygames.com/games/k-sniper-challenge-3d/cover-1583233999693.png'  
  },  
  'smash-karts': {  
    title: 'Smash Karts',  
    category: 'racing',  
    categoryName: 'Racing',  
    stars: '★★★★★',  
    plays: '654K plays',  
    description: 'Smash Karts is a multiplayer kart battle game where you race and battle simultaneously. Collect weapons, eliminate opponents, and be the last kart standing!',  
    developer: 'Kart Games',  
    releaseDate: '2020',  
    controls: 'Arrow Keys, WASD',  
    similar: ['traffic-rider-vvq', 'racing-limits', 'mx-offroad-master'],  
    imageUrl: 'https://img.crazygames.com/games/smash-karts/cover-1584975129006.png'  
  },  
  'snake-io': {  
    title: 'Snake IO',  
    category: 'action',  
    categoryName: 'Action',  
    stars: '★★★★☆',  
    plays: '489K plays',  
    description: 'Snake IO is a multiplayer snake game where you grow by eating pellets and defeating other players. Become the biggest snake in the arena!',  
    developer: 'IO Games',  
    releaseDate: '2017',  
    controls: 'Mouse',  
    similar: ['bloxdhop-io', 'kour-io', 'playground'],  
    imageUrl: 'https://img.crazygames.com/games/snake-io/cover-1583401205146.png'  
  },  
  'kour-io': {  
    title: 'Kour IO',  
    category: 'shooting',  
    categoryName: 'Shooting',  
    stars: '★★★★☆',  
    plays: '412K plays',  
    description: 'Kour IO is a multiplayer parkour shooting game where you run, jump, and shoot your way to victory. Compete against players worldwide in this fast-paced action game.',  
    developer: 'IO Games',  
    releaseDate: '2018',  
    controls: 'Mouse, WASD',  
    similar: ['bullet-force-multiplayer', 'skillwarz', 'k-sniper-challenge-3d'],  
    imageUrl: 'https://img.crazygames.com/games/kour-io/cover-1583235980400.png'  
  },  
  'count-masters-stickman-games': {  
    title: 'Count Masters: Stickman Games',  
    category: 'action',  
    categoryName: 'Action',  
    stars: '★★★★★',  
    plays: '532K plays',  
    description: 'Count Masters: Stickman Games is a crowd runner game where you control a group of stickmen. Collect more stickmen, avoid obstacles, and defeat enemies to reach the finish line.',  
    developer: 'Stickman Studios',  
    releaseDate: '2021',  
    controls: 'Mouse, Touch',  
    similar: ['stickman-epic', 'stickman-ww2', 'playground'],  
    imageUrl: 'https://img.crazygames.com/games/count-masters-stickman-games/cover-1664442257134.png'  
  }  
};